Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 300

  def provision_common(vm)
    vm.vm.provision "shell", privileged: true, inline: <<-SHELL
      apt-get install -y python3 python3-pip
      cp /vagrant/scripts/* /home/vagrant/
      chown vagrant:vagrant /home/vagrant/*.py
      chmod +x /home/vagrant/*.py
    SHELL
  end

  config.vm.define "p1" do |p1|
    p1.vm.hostname = "p1"
    p1.vm.network "private_network", ip: "192.168.56.11"
    provision_common(p1)
    p1.vm.provision "shell", privileged: true, inline: <<-SHELL
      cp /vagrant/files/* /home/vagrant/
      chown vagrant:vagrant /home/vagrant/mainfile.txt /home/vagrant/coveredfile.txt
    SHELL
  end

  config.vm.define "uz" do |uz|
    uz.vm.hostname = "uz"
    uz.vm.network "private_network", ip: "192.168.56.12"
    provision_common(uz)
  end

  config.vm.define "p2" do |p2|
    p2.vm.hostname = "p2"
    p2.vm.network "private_network", ip: "192.168.56.13"
    provision_common(p2)
  end
end
